// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	order "e-commerce-api/feature/order"

	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: token, orderID
func (_m *OrderService) Cancel(token interface{}, orderID uint) error {
	ret := _m.Called(token, orderID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Confirm provides a mock function with given fields: token, orderID
func (_m *OrderService) Confirm(token interface{}, orderID uint) error {
	ret := _m.Called(token, orderID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: token, carts
func (_m *OrderService) Create(token interface{}, carts []order.Cart) (order.Core, error) {
	ret := _m.Called(token, carts)

	var r0 order.Core
	if rf, ok := ret.Get(0).(func(interface{}, []order.Cart) order.Core); ok {
		r0 = rf(token, carts)
	} else {
		r0 = ret.Get(0).(order.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, []order.Cart) error); ok {
		r1 = rf(token, carts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: token, history
func (_m *OrderService) GetAll(token interface{}, history string) ([]order.Core, error) {
	ret := _m.Called(token, history)

	var r0 []order.Core
	if rf, ok := ret.Get(0).(func(interface{}, string) []order.Core); ok {
		r0 = rf(token, history)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, string) error); ok {
		r1 = rf(token, history)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderBuy provides a mock function with given fields: token, orderID
func (_m *OrderService) GetOrderBuy(token interface{}, orderID uint) (order.Core, error) {
	ret := _m.Called(token, orderID)

	var r0 order.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint) order.Core); ok {
		r0 = rf(token, orderID)
	} else {
		r0 = ret.Get(0).(order.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint) error); ok {
		r1 = rf(token, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderSell provides a mock function with given fields: token, orderID
func (_m *OrderService) GetOrderSell(token interface{}, orderID uint) (order.Core, error) {
	ret := _m.Called(token, orderID)

	var r0 order.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint) order.Core); ok {
		r0 = rf(token, orderID)
	} else {
		r0 = ret.Get(0).(order.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint) error); ok {
		r1 = rf(token, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrderService interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderService(t mockConstructorTestingTNewOrderService) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
