// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	product "e-commerce-api/feature/product"
)

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

// Add provides a mock function with given fields: token, newProduct, fileHeader
func (_m *ProductService) Add(token interface{}, newProduct product.Core, fileHeader *multipart.FileHeader) error {
	ret := _m.Called(token, newProduct, fileHeader)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, product.Core, *multipart.FileHeader) error); ok {
		r0 = rf(token, newProduct, fileHeader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: token, productID
func (_m *ProductService) Delete(token interface{}, productID uint) error {
	ret := _m.Called(token, productID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page
func (_m *ProductService) GetAll(page uint) ([]product.Core, error) {
	ret := _m.Called(page)

	var r0 []product.Core
	if rf, ok := ret.Get(0).(func(uint) []product.Core); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: productID
func (_m *ProductService) GetByID(productID uint) (product.Core, error) {
	ret := _m.Called(productID)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(uint) product.Core); ok {
		r0 = rf(productID)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: token, productID, updateProduct, fileHeader
func (_m *ProductService) Update(token interface{}, productID uint, updateProduct product.Core, fileHeader *multipart.FileHeader) error {
	ret := _m.Called(token, productID, updateProduct, fileHeader)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint, product.Core, *multipart.FileHeader) error); ok {
		r0 = rf(token, productID, updateProduct, fileHeader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProductService interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductService(t mockConstructorTestingTNewProductService) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
