// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	product "e-commerce-api/feature/product"

	mock "github.com/stretchr/testify/mock"
)

// ProductData is an autogenerated mock type for the ProductData type
type ProductData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userID, newProduct
func (_m *ProductData) Add(userID uint, newProduct product.Core) error {
	ret := _m.Called(userID, newProduct)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, product.Core) error); ok {
		r0 = rf(userID, newProduct)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountProduct provides a mock function with given fields:
func (_m *ProductData) CountProduct() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: userID, productID
func (_m *ProductData) Delete(userID uint, productID uint) error {
	ret := _m.Called(userID, productID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: limit, offset
func (_m *ProductData) GetAll(limit int, offset int) ([]product.Core, error) {
	ret := _m.Called(limit, offset)

	var r0 []product.Core
	if rf, ok := ret.Get(0).(func(int, int) []product.Core); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: productID
func (_m *ProductData) GetByID(productID uint) (product.Core, error) {
	ret := _m.Called(productID)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(uint) product.Core); ok {
		r0 = rf(productID)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userID, productID, updateProduct
func (_m *ProductData) Update(userID uint, productID uint, updateProduct product.Core) error {
	ret := _m.Called(userID, productID, updateProduct)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, product.Core) error); ok {
		r0 = rf(userID, productID, updateProduct)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProductData interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductData creates a new instance of ProductData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductData(t mockConstructorTestingTNewProductData) *ProductData {
	mock := &ProductData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
